### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by GithungoIan** [VirtusLab-Open-Source/strapi-plugin-navigation#106]
I've added the strapi-plugin-navigation plugin to my project using yarn and ran the yarn build command. The build was successful but trying to run the yarn develop command I keep get this error 

``` 
⛔️ Server wasn't able to start properly.
... node_modules/strapi-plugin-navigation/models/navigationItem.js:20
        _?.related.forEach(entity => {
          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Comment by cyp3rius** [comment]
See the #95, same case with ES support.
