### ISSUE TITLE
Error after update to v1.1.0 on node@13 and earlier

### ISSUE THREAD

**Issue by shyr1punk** [VirtusLab-Open-Source/strapi-plugin-navigation#107]
In sources used optional chaining operator supported in node@14

```
[2021-11-19T10:31:36.868Z] debug ⛔️ Server wasn't able to start properly.
[2021-11-19T10:31:36.869Z] error /Users/a18633629/dev/smartmarket-portal-admin/node_modules/strapi-plugin-navigation/models/navigationItem.js:20
        _?.related.forEach(entity => {
          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadFiles (/Users/a18633629/dev/smartmarket-portal-admin/node_modules/strapi/lib/load/load-files.js:37:13)
    at async loadPlugins (/Users/a18633629/dev/smartmarket-portal-admin/node_modules/strapi/lib/core/load-plugins.js:53:19)
    at async module.exports (/Users/a18633629/dev/smartmarket-portal-admin/node_modules/strapi/lib/core/load-plugins.js:12:19)
```

1) Replace optional chaining (preffered)
2) Update your node version in package.json > engines

**Comment by shyr1punk** [comment]
duplicate #106
