### ISSUE TITLE
Public API specification - tree and rfr throws 500 server error

### ISSUE THREAD

**Issue by voytech-net** [VirtusLab-Open-Source/strapi-plugin-navigation#111]
Hello,

I have installed plugin's version 1.1.1 and I am currently experiencing an issue where I am not able to get items from REST API with type=tree or type=rfr, type=flat is working ok.

Here is the stacktrace:
`TypeError: Cannot read property 'find' of undefined
    at /Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-navigation/services/utils/functions.js:115:60
    at itemParser (/Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-navigation/services/navigation.js:330:33)
    at /Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-navigation/services/navigation.js:395:20
    at Array.map (<anonymous>)
    at Object.renderTree (/Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-navigation/services/navigation.js:395:8)
    at Object.renderType (/Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-navigation/services/navigation.js:342:41)
    at async /Users/vojtaesner/www/metrostav-api/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/Users/vojtaesner/www/metrostav-api/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:88:3)
    at async /Users/vojtaesner/www/metrostav-api/node_modules/strapi-utils/lib/policy.js:68:5
    at async /Users/vojtaesner/www/metrostav-api/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /Users/vojtaesner/www/metrostav-api/node_modules/strapi/lib/middlewares/xss/index.js:26:9`

Could you please try on your end whether you are experiencing the same? Thank you.

**Comment by cyp3rius** [comment]
Fix released as version `1.1.2`
