### ISSUE TITLE
Issue with install "strapi-plugin-navigation": "^2.0.0-beta.1"

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#130]
I followed the recommended installation as per plugin https://www.npmjs.com/package/strapi-plugin-navigation

I am using a plain vanilla install of strapi 4.0.3

yarn add strapi-plugin-navigation@latest
yarn build

when i run build i get following error:

Error: Plugin name "Navigation" is not in kebab (an-example-of-kebab-case)
    at validatePluginName (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:20:11)
    at getEnabledPlugins (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:71:7)
    at module.exports (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/strapi/lib/commands/build.js:24:25)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/strapi/bin/strapi.js:52:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any ideas what might be causing this? is it a configuration error at my end?

**Comment by cyp3rius** [comment]
Hello @mattmillen888 ,

Fix has been releases as `v2.0.0-beta.2`
