### ISSUE TITLE
 Cannot read property 'associations' of undefined

### ISSUE THREAD

**Issue by EvaChuks** [VirtusLab-Open-Source/strapi-plugin-navigation#140]
I got this error when am trying to upload an image from nextjs frontend to strapi. 

```
[2022-01-20T15:18:23.548Z] error TypeError: Cannot read property 'associations' of undefined
    at D:\websites\fineback\node_modules\strapi-connector-bookshelf\lib\relations.js:259:46
    at Array.forEach (<anonymous>)
    at D:\websites\fineback\node_modules\strapi-connector-bookshelf\lib\relations.js:253:16
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (D:\websites\fineback\node_modules\strapi-connector-bookshelf\lib\relations.js:105:68)
[2022-01-20T15:18:23.549Z] debug POST /upload (8265 ms) 500

=========Database========
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'sqlite',
        filename: env('DATABASE_FILENAME', '.tmp/data.db'),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});

===========model==================
{
  "kind": "collectionType",
  "collectionName": "sports",
  "info": {
    "name": "Sport",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "uid",
      "targetField": "name"
    },
    "date": {
      "type": "datetime"
    },
    "time": {
      "type": "string"
    },
    "image": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false,
      "pluginOptions": {}
    },
    "detail": {
      "type": "richtext"
    },
    "user": {
      "plugin": "users-permissions",
      "model": "user",
      "via": "sports"
    }
  }
}

=====plugin.js======
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: "cloudinary",
    providerOptions: {
      cloud_name: env("CLOUDINARY_NAME"),
      api_key: env("CLOUDINARY_KEY"),
      api_secret: env("CLOUDINARY_SECRET"),
    },
    actionOptions: {
      upload: {},
      delete: {},
    },
  },
  // ...
  // folder: env("CLOUDINARY_FOLDER"),
});

```

Strapi version: 3.6.8

**Comment by cyp3rius** [comment]
Closing as we're no longer going to maintain `v3`.
