### ISSUE TITLE
renderNavigation Endpoint returns an error when querying the related field 

### ISSUE THREAD

**Issue by motion-work** [VirtusLab-Open-Source/strapi-plugin-navigation#158]
I'm trying to get the related page of the navigation item via the ***GraphQL endpoint*** (renderNavigation).

Querying the `related` field returns the following error: 

```json
"errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"NavigationItem.related\".",
      "locations": [
        {
          "line": 8,
          "column": 5
        }
      ],
      "path": [
        "renderNavigation",
        0,
        "related"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Expected Iterable, but did not find one for field \"NavigationItem.related\".",
          "stacktrace": [
            "GraphQLError: Expected Iterable, but did not find one for field \"NavigationItem.related\".",
            "    at completeListValue (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/graphql/execution/execute.js:641:11)",
            "    at completeValue (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/graphql/execution/execute.js:572:12)",
            "    at /Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/graphql/execution/execute.js:469:16",
            "    at async Promise.all (index 5)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async execute (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:205:20)",
            "    at async processGraphQLRequest (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:148:28)",
            "    at async processHTTPRequest (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/runHttpQuery.js:187:30)",
            "    at async /Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/apollo-server-koa/dist/ApolloServer.js:82:59",
            "    at async bodyParser (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/koa-bodyparser/index.js:95:5)",
            "    at async cors (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/@koa/cors/index.js:98:16)",
            "    at async returnBodyMiddleware (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)",
            "    at async policiesMiddleware (/Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)",
            "    at async /Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5",
            "    at async /Users/nattha/Development/backend.strapi-nuxt.tech/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5"
          ]
        }
      }
    }

```

Here's my query:

```js
{
  renderNavigation(navigationIdOrSlug: "main", type: TREE, path: "/home") {
    title
    type
    path
    externalPath
    uiRouterKey
    related {
      ... on Page {
        title
      }
    }
    items {
      id
      title
      path
      type
      uiRouterKey
    }
  }
}

```

The REST endpoint works as expected:

`http://localhost:1337/api/navigation/render/1?path=/home/team`

```json
[
  {
    "id": 1,
    "title": "Home",
    "type": "INTERNAL",
    "path": "home",
    "externalPath": null,
    "uiRouterKey": "home",
    "menuAttached": false,
    "order": 1,
    "createdAt": "2022-02-21T11:57:00.212Z",
    "updatedAt": "2022-02-21T11:58:36.550Z",
    "audience": [],
    "parent": null,
    "related": [
      {
        "id": 20,
        "title": "Home",
        "createdAt": "2022-02-16T09:35:39.191Z",
        "updatedAt": "2022-02-16T10:56:17.392Z",
        "publishedAt": "2022-02-16T09:35:40.828Z",
        "locale": "de",
        "hidden": null,
        "slug": "home",
        "__contentType": "api::page.page",
        "navigationItemId": 1
      }
    ],
    "items": null
  },
  {
    "id": 2,
    "title": "Team",
    "type": "INTERNAL",
    "path": "team",
    "externalPath": null,
    "uiRouterKey": "team",
    "menuAttached": false,
    "order": 1,
    "createdAt": "2022-02-21T13:57:49.060Z",
    "updatedAt": "2022-02-21T13:57:57.456Z",
    "audience": [],
    "parent": {
      "id": 1,
      "title": "Home",
      "type": "INTERNAL",
      "path": "home",
      "externalPath": null,
      "uiRouterKey": "home",
      "menuAttached": false,
      "order": 1,
      "createdAt": "2022-02-21T11:57:00.212Z",
      "updatedAt": "2022-02-21T11:58:36.550Z"
    },
    "related": [
      {
        "id": 24,
        "title": "Team",
        "createdAt": "2022-02-21T11:11:47.706Z",
        "updatedAt": "2022-02-21T11:11:49.080Z",
        "publishedAt": "2022-02-21T11:11:49.077Z",
        "locale": "de",
        "hidden": null,
        "slug": "team",
        "__contentType": "api::page.page",
        "navigationItemId": 2
      }
    ],
    "items": null
  }
]
```

**Comment by cyp3rius** [comment]
Fixed in `v2.0.5`
