### ISSUE TITLE
GraphQL NavigationItem type has incorrect type for parent

### ISSUE THREAD

**Issue by AreeseDT** [VirtusLab-Open-Source/strapi-plugin-navigation#202]
The GraphQL type for `NavigationItem` defines parent as an Int. When executing the `renderNavigation` query with render type of `FLAT`, errors are thrown due to parent being an instance of `NavigationItem`. If the render type is `TREE` or `RFR`, the value of parent always appears to be `null`.

Relevant type from the graphql schema:
```
type NavigationItem {
    ...
    order: Int!
    parent: Int
    master: Int
    ...
}
```

Error message when render type is `FLAT`:
```
{
  "message": "Int cannot represent non-integer value: { id: 1, title: \"Pages\", type: \"WRAPPER\", path: \"pages\", externalPath: null, uiRouterKey: \"pages\", menuAttached: true, order: 1, collapsed: false, createdAt: \"2022-04-13T20:22:11.895Z\", updatedAt: \"2022-04-13T21:02:33.036Z\" }",
  "locations": [
    {
      "line": 25,
      "column": 3
    }
  ],
  "path": [
    "renderNavigation",
    1,
    "parent"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "message": "Int cannot represent non-integer value: { id: 1, title: \"Pages\", type: \"WRAPPER\", path: \"pages\", externalPath: null, uiRouterKey: \"pages\", menuAttached: true, order: 1, collapsed: false, createdAt: \"2022-04-13T20:22:11.895Z\", updatedAt: \"2022-04-13T21:02:33.036Z\" }",
      "stacktrace": [
        "GraphQLError: Int cannot represent non-integer value: { id: 1, title: \"Pages\", type: \"WRAPPER\", path: \"pages\", externalPath: null, uiRouterKey: \"pages\", menuAttached: true, order: 1, collapsed: false, createdAt: \"2022-04-13T20:22:11.895Z\", updatedAt: \"2022-04-13T21:02:33.036Z\" }",
        "    at GraphQLScalarType.serializeInt [as serialize] (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\graphql\\type\\scalars.js:49:11)",
        "    at completeLeafValue (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\graphql\\execution\\execute.js:653:37)",
        "    at completeValue (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\graphql\\execution\\execute.js:578:12)",
        "    at D:\\Projects\\Sandbox\\plugin-test\\node_modules\\graphql\\execution\\execute.js:469:16",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async Promise.all (index 8)",
        "    at async Promise.all (index 1)",
        "    at async Promise.all (index 0)",
        "    at async execute (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:205:20)",
        "    at async Object.processGraphQLRequest (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:139:28)",
        "    at async processHTTPRequest (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:179:30)",
        "    at async D:\\Projects\\Sandbox\\plugin-test\\node_modules\\apollo-server-koa\\dist\\ApolloServer.js:82:59",
        "    at async bodyParser (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\koa-bodyparser\\index.js:95:5)",
        "    at async returnBodyMiddleware (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\@strapi\\strapi\\lib\\services\\server\\compose-endpoint.js:52:18)",
        "    at async policiesMiddleware (D:\\Projects\\Sandbox\\plugin-test\\node_modules\\@strapi\\strapi\\lib\\services\\server\\policy.js:24:5)"
      ]
    }
  }
}
```

**Comment by cyp3rius** [comment]
Fix released in version `2.0.13`
