### ISSUE TITLE
Single Type with multiple locale crashs TREE and RFR api view

### ISSUE THREAD

**Issue by skyclb** [VirtusLab-Open-Source/strapi-plugin-navigation#230]
In my project i experienced the follow error. In my case, it seems to happen when having setup multilang navigation and single type for atleast two languages (did not test on a fresh install). After creation when calling the api with `type=TREE`, i receive below error.

Versions
@strapi/plugin-i18n: 4.1.12
@strapi/strapi: 4.1.12
strapi-plugin-navigation: 2.1.0-beta.1

**Update:**
It seems that this piece of code is responsible for the error, by return `undefined`. Removing this lines completly fixes the error for me. But i wonder whats `isAvailable` used for and why is it limited to 1 entry since it queries for all content type languages? Not sure what `viaSettingsPage` is used for.

_File: strapi-plugin-navigation/server/services/common.js:L63_
```
if (isSingleType) {
    if (isSingleTypeWithPublishFlow) {
        const itemsCountOrBypass = isSingleTypeWithPublishFlow ?
            await strapi.query(uid).count({
                where: {
                    published_at: { $notNull: true },
                },
            }) :
            true;
        return returnType(itemsCountOrBypass !== 0);
    }
    const isAvailable = await strapi.query(uid).count({});          <----
    return isAvailable === 1 ?                                      <----
        returnType(true) :                                          <----
        (viaSettingsPage ? returnType(false) : undefined);          <----
}
```

Error Message:
```
Error: Model undefined not found
    at Database.query (/home/user/Documents/_strapi_v4/node_modules/@strapi/database/lib/index.js:44:13)
    at Strapi.query (/home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/Strapi.js:503:20)
    at /home/user/Documents/_strapi_v4/node_modules/strapi-plugin-navigation/server/utils/functions.js:42:23
    at Array.map (<anonymous>)
    at templateNameFactory (/home/user/Documents/_strapi_v4/node_modules/strapi-plugin-navigation/server/utils/functions.js:40:10)
    at Object.renderType (/home/user/Documents/_strapi_v4/node_modules/strapi-plugin-navigation/server/services/client.js:197:83)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.render (/home/user/Documents/_strapi_v4/node_modules/strapi-plugin-navigation/server/services/client.js:20:16)
    at async returnBodyMiddleware (/home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/home/user/Documents/_strapi_v4/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/middlewares/body.js:51:9
    at async /home/user/Documents/_strapi_v4/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
```

**Comment by cyp3rius** [comment]
@skyclb thanks for your contribution. Released as part of major version `2.1.0`
