### ISSUE TITLE
error: Expected New to be a objectType, saw GraphQLScalarType

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#238]
When i turn on navigation in plugins.js i get this error::

module.exports = ({ env }) => ({
  navigation: { enabled: true }, /// This one
  graphql: {
    enabled: true,
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
});

The Error::::

Error: Expected New to be a objectType, saw GraphQLScalarType
    at SchemaBuilder.getObjectType (/backend/node_modules/nexus/dist/builder.js:890:19)
    at /backend/node_modules/nexus/dist/builder.js:719:36
    at Array.forEach (<anonymous>)
    at SchemaBuilder.buildUnionMembers (/backend/node_modules/nexus/dist/builder.js:718:17)
    at types (/backend/node_modules/nexus/dist/builder.js:667:31)
    at resolveThunk (/backend/node_modules/graphql/type/definition.js:480:40)
    at defineTypes (/backend/node_modules/graphql/type/definition.js:944:15)
    at GraphQLUnionType.getTypes (/node_modules/graphql/type/definition.js:900:26)
    at collectReferencedTypes (/backend/node_modules/graphql/type/schema.js:356:59)
    at new GraphQLSchema (/backend/node_modules/graphql/type/schema.js:148:9)
error Command failed with exit code 1.

Any ideas why this is happening?

**Comment by mattmillen888** [comment]
It seems like since i updated to 2.1.0 it no longer shows in admin panel. is this the reason im getting the error because it is no longer there?

**Comment by mattmillen888** [comment]
I managed to solve this by just clearing out the old menu on a backup and starting again
