### ISSUE TITLE
Extending both the backend and the frontend of the plugin

### ISSUE THREAD

**Issue by TasosBak** [VirtusLab-Open-Source/strapi-plugin-navigation#329]
Hello! I am trying to customize the plugin in various ways including both the backend and the frontend. I am using strapi@4.9.2

The steps I followed are:

1. Navigate to `src/plugins` inside my project
2. Run `git clone https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation.git`
3. Create `config/plugin.js` file and
4. Add
`
    module.exports = {
      'strapi-plugin-navigation': {
        enabled: true,
        resolve: './src/plugins/strapi-plugin-navigation' 
      },
    };
`
5. Navigate to `src/plugins/strapi-plugin-navigation` (created in step 2)
6. Run `yarn && yarn build`
7. Navigate to project root and
8. Run `rm -rf .cache build && yarn build && yarn develop`

I see the plugin in the plugin page `http://localhost:1337/admin/list-plugins` but nowhere else. It isn't showing in the left menu or in the settings so that I can enable the render routes. 

Any suggestions?

**Comment by cyp3rius** [comment]
Hello @TasosBak,

Most of the steps you're doing right. Except pointing to the proper directory of the plugin. We've got TS version of it so to run properly by Strapi you must:

1. In plugin directory: `yarn develop` (spying changes) or `yarn build` (to rebuild the plugin)
2. In the `config/plugins.js` the line of `resolve` should point to `./src/plugins/strapi-plugin-navigation/build` - the TSC prepares the js files in `build` directory.
3. Add script to your project `"develop": "strapi develop --watch-admin"` and run your Strapi instance like `yarn develop`

Everything should work as expected.

**Comment by TasosBak** [comment]
You are right I missed that!

Now I get this error

```
$ strapi develop --watch-admin
Error: Unknown target plugin::navigation.navigation
        at createJoinTable (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\metadata\relations.js:399:11)
        at createOneToMany (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\metadata\relations.js:78:5)
        at createRelation (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\metadata\relations.js:336:14)
        at createMetadata (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\metadata\index.js:76:11)
        at new Database (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\index.js:19:21)
        at Database.init (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\index.js:119:14)
        at Strapi.bootstrap (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:417:30)
        at Strapi.load (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:488:16)
        at async Strapi.start (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:216:9)
        
[2023-04-26 14:50:48.796] debug: ⛔️ Server wasn't able to start properly.
[2023-04-26 14:50:48.801] error: Error on attribute localizations in model navigation(plugin::strapi-plugin-navigation.navigation): Unknown target plugin::navigation.navigation
Error: Error on attribute localizations in model navigation(plugin::strapi-plugin-navigation.navigation): Unknown target plugin::navigation.navigation        
    at createMetadata (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\metadata\index.js:83:15)
    at new Database (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\index.js:19:21)
    at Database.init (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\database\lib\index.js:119:14)
    at Strapi.bootstrap (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:417:30)
    at Strapi.load (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:488:16)
    at async Strapi.start (C:\Users\userrr\Documents\Projects\menus\node_modules\@strapi\strapi\lib\Strapi.js:216:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cyp3rius** [comment]
in `config/plugins.js` try to change `strapi-plugin-navigation` to `navigation` as probably the uid is not generated properly.

**Comment by TasosBak** [comment]
That was it! Thank you very much!
