### ISSUE TITLE
Mysql Error 1062 ER_DUP_ENTRY

### ISSUE THREAD

**Issue by Bryelmo** [VirtusLab-Open-Source/strapi-plugin-navigation#334]
I created the 24th menu (id:24) and Strapi created the relative translated menu (id:25).
I cannot launch Strapi anymore as `npm run develop` because I get the following error:

`Starting the compilation for TypeScript files in /Users/bryelmo/Projects/wfpcms
Error: ER_DUP_ENTRY: Duplicate entry 'start-app-navigation-it' for key 'navigations_slug_unique'
    at Sequence._packetToError (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/bryelmo/Projects/wfpcms/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/execution/runner.js:300:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (/Users/bryelmo/Projects/wfpcms/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/Users/bryelmo/Projects/wfpcms/node_modules/@strapi/database/lib/query/query-builder.js:481:22)
    at async Object.create (/Users/bryelmo/Projects/wfpcms/node_modules/@strapi/database/lib/entity-manager/index.js:224:19)
    at async /Users/bryelmo/Projects/wfpcms/node_modules/strapi-plugin-navigation/server/i18n/navigationSetupStrategy.js:50:40
    at async Promise.all (index 11) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: "Duplicate entry 'start-app-navigation-it' for key 'navigations_slug_unique'",
  sqlState: '23000',
  index: 0,
  sql: "insert into `navigations` (`created_at`, `locale_code`, `name`, `slug`, `updated_at`, `visible`) values ('2023-05-09 21:36:04.523', 'it', 'StartApp Navigation', 'start-app-navigation-it', '2023-05-09 21:36:04.523', true)"
}`

It seems that Strapi try to INSERT the last translated menu during the startup and fails.
I tried with an another database backup with all the last stored navigations until to id:22 (en-EN) and id: 23(it-IT) and everything works fine but every time I try to add another menu (24, 25) I get this error after stopping and restarting Strapi.

- Tested on Strapi v4.9.2 or v4.10.2
- NPM v9.5.0
- Node v18.15.0
- Mysql Server v5.7

**Comment by Bryelmo** [comment]
Update:
I noticed that I had the .strapi.updater.json with:
`{
	"latest": "4.10.2",
	"lastUpdateCheck": 1683634475390,
	"lastNotification": 1683646052673
}`

After deleting it and recreating it now it's:
`{
	"latest": "4.10.2",
	"lastUpdateCheck": 1683703932764
}`

Actually, the issue with this updated file seems solved.

**Comment by TasosBak** [comment]
Hello all! I had this issue #290 and I upgraded strapi to 4.10.6. Now I am getting the ER_DUP_ENTRY error and can't spin up my project. The only way to spin it up is to delete _navigations_ rows. 

Deleting .strapi.updater.json didn't work, any ideas?

**Comment by TasosBak** [comment]
I found out that I don't have a problem while working with one navigation instance with however many locales added to it.

The problems begin when I add a new navigation. 

I get this error in the admin
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/15340410/7010cff3-4cdc-4101-a988-c294ed751b45)

and in the console:
```
error: insert into `navigations_localizations_links` (`inv_navigation_id`, `navigation_id`, `navigation_order`) values (28, 27, 1), (29, 27, 2) on duplicate key update `navigation_order` = values(`navigation_order`) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction    
Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
    at Sequence._packetToError (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)    
    at Query.ErrorPacket (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\dialects\mysql\index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\dialects\mysql\index.js:126:12)
    at executeQuery (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)       
    at Client_MySQL.query (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\client.js:146:12)
    at C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\execution\transaction.js:363:24
    at new Promise (<anonymous>)
    at trxClient.query (C:\Users\user\Documents\Projects\strapi\navigationPOC\node_modules\knex\lib\execution\transaction.js:358:12)
```
