### ISSUE TITLE
Error dependency on installation

### ISSUE THREAD

**Issue by twog93** [VirtusLab-Open-Source/strapi-plugin-navigation#354]
Hello,

Catching errors when executing "yarn build"

```
Error: Cannot find module 'react-router'
Require stack:
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\webpack.alias.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\webpack.config.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\utils\get-custom-webpack-config.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\utils\index.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\index.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\builders\admin.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\builders\index.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\actions\build-command\action.js- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\utils\helpers.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\actions\admin\create-user\command.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\lib\commands\index.js
- C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\strapi\bin\strapi.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\webpack.alias.js:41:46
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (C:\wamp64\www\strapi_modele_dgap\node_modules\@strapi\admin\webpack.alias.js:40:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
Done in 8.26s.
```

Environnement: 
Npm : 9.5.1
Yarn : 1.22.19
Node : 18.16.0
current dependencies: 

   "  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.7",
    "@strapi/plugin-i18n": "^4.10.2",
    "@strapi/plugin-seo": "^1.8.0",
    "@strapi/plugin-users-permissions": "4.10.2",
    "@strapi/provider-email-nodemailer": "^4.11.1",
    "@strapi/strapi": "4.10.2",
    "axios": "^1.4.0",
    "better-sqlite3": "8.0.1",
    "node-fetch": "^3.3.1",
    "nodemailer": "^6.9.3",
    "pg": "^8.11.0",
    "strapi-plugin-import-export-entries": "^1.19.2",
    "strapi-plugin-navigation": "^2.2.11",
    "strapi-plugin-populate-deep": "^2.0.0"
  },

could you help me?

**Comment by cyp3rius** [comment]
Hello @twog93, I'm not seeing our plugin as dependency so not sure what cause your issue.

**Comment by twog93** [comment]
Sorry wrong prompt, i update my issue

**Comment by cyp3rius** [comment]
Check please the newest versions of plugin is issue persist still.

**Comment by cyp3rius** [comment]
Closing as no response.
