### ISSUE TITLE
Error after deleting type

### ISSUE THREAD

**Issue by Xromern** [VirtusLab-Open-Source/strapi-plugin-navigation#355]
Hi,
I get an error after deleting a type which used in navigation

```
Error: Model api::test.test not found
    at Database.query (backend/node_modules/@strapi/database/lib/index.js:48:13)
    at Strapi.query (/backend/node_modules/@strapi/strapi/lib/Strapi.js:569:20)
    at /backend/src/plugins/strapi-plugin-navigation-master/build/server/services/common.js:217:18
    at Array.map (<anonymous>)
    at Object.getRelatedItems (/backend/src/plugins/strapi-plugin-navigation-master/build/server/services/common.js:215:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getById (/backend/src/plugins/strapi-plugin-navigation-master/build/server/services/admin.js:88:26)
    at async returnBodyMiddleware (/backend/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/backend/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/backend/node_modules/koa-static/index.js:59:5)
```

Steps: 
1. Create type 
2. Add created type to navigation
3. Delete created type
4. Back to navigation and get an error

"@strapi/strapi": "4.11.3",
"strapi-plugin-navigation": "^2.2.11"

**Comment by cyp3rius** [comment]
Fixed in `v2.2.13`
