### ISSUE TITLE
CastError: Cast to ObjectId failed for value "1" at path "_id" for model "navigation"

### ISSUE THREAD

**Issue by jeffisowens** [VirtusLab-Open-Source/strapi-plugin-navigation#83]
I'm trying to test the navigation rendering via http://localhost:1337/navigation/render/1?type=%22tree%22.

I get a 500 Internal Server Error and in the logs I see the above CastError.

This is my initial setup:

![image](https://user-images.githubusercontent.com/4451052/123996210-175d1080-d99d-11eb-8366-9f8f4abb01c4.png)

Home is a published single type page.

Components and test2 are published collection type pages

Any help is appreciated!

**Comment by Kronos66** [comment]
Hi @jeffisowens Could you add stack trace and explain why you have in URL something like this: `type="tree"`?

**Comment by jeffisowens** [comment]
Tree shouldn't have been in quotes, but it's the same error if it is.

Full log:

`Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2021-07-01T13:21:52.637Z] error CastError: Cast to ObjectId failed for value "1" at path "_id" for model "navigation"
    at model.Query.exec (/Users/jdowens/Documents/Sites/portal-cms/node_modules/mongoose/lib/query.js:4371:21)
    at model.Query.Query.then (/Users/jdowens/Documents/Sites/portal-cms/node_modules/mongoose/lib/query.js:4463:15)
    at find (/Users/jdowens/Documents/Sites/portal-cms/node_modules/strapi-connector-mongoose/lib/queries.js:444:8)
    at Object.findOne (/Users/jdowens/Documents/Sites/portal-cms/node_modules/strapi-connector-mongoose/lib/queries.js:448:27)
    at fn (/Users/jdowens/Documents/Sites/portal-cms/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.findOne (/Users/jdowens/Documents/Sites/portal-cms/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.renderType (/Users/jdowens/Documents/Sites/portal-cms/node_modules/strapi-plugin-navigation/services/navigation.js:256:20)
[2021-07-01T13:21:52.639Z] debug GET /navigation/render/1 (18 ms) 500
[2021-07-01T13:21:53.250Z] debug GET /favicon.ico (1 ms) 200`

**Comment by cyp3rius** [comment]
@jeffisowens as I see you're using MongoDB and I assume that you're trying to retrieve the navigation with not valid id because Mongo generates an alphanumeric ids rather than integers.

``` http://localhost:1337/navigation/render/<id or slug>?type=tree```

That how your call should look like. You should replace `<id or slug>` by proper navigation id or it slug. The initial navigation is created with slug `main-navigation` try to call:

``` http://localhost:1337/navigation/render/main-navigation?type=tree```

and check if work.

**Comment by jeffisowens** [comment]
Thanks! That works!
