### ISSUE TITLE
Strapi crashes after uninstall

### ISSUE THREAD

**Issue by apokalipscke** [VirtusLab-Open-Source/strapi-plugin-navigation#85]
I tried different ways to uninstall this plugin, always resulting in crashed application.

No matter if I do it with `npm remove strapi-plugin-navigation` or `strapi uninstall navigation --delete-files` or from the backend.

Log:

```
strapi     | [2021-07-07T08:23:05.873Z] info Uninstalling navigation...
strapi     | [2021-07-07T08:23:08.276Z] info File changed: /srv/app/package.json
strapi     | [2021-07-07T08:23:27.177Z] info File changed: /srv/app/yarn.lock
strapi     | [2021-07-07T08:24:41.460Z] info File changed: /srv/app/build/*
[...]
strapi     | [2021-07-07T08:24:41.742Z] debug DELETE /admin/plugins/uninstall/navigation (95899 ms) 200
strapi     | [2021-07-07T08:24:41.742Z] info The server is restarting
strapi     |
strapi     | [2021-07-07T08:24:49.043Z] debug ⛔️ Server wasn't able to start properly.
strapi     | [2021-07-07T08:24:49.045Z] error TypeError: Cannot read property 'models' of undefined
strapi     |     at DatabaseManager.getModelsByPluginName (/srv/app/node_modules/strapi-database/lib/database-manager.js:158:86)
strapi     |     at Object.getNature (/srv/app/node_modules/strapi-utils/lib/models.js:41:30)
strapi     |     at /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:185:21
strapi     |     at Array.forEach (<anonymous>)
strapi     |     at updateModel (/srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:178:40)
strapi     |     at async module.exports (/srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:702:28)
strapi     |     at async Promise.all (index 1)
strapi     |     at async mountConnection (/srv/app/node_modules/strapi-connector-bookshelf/lib/index.js:87:31)
strapi     |     at async Promise.all (index 0)
strapi     |     at async Object.initialize (/srv/app/node_modules/strapi-database/lib/connector-registry.js:30:9)
strapi     |     at async DatabaseManager.initialize (/srv/app/node_modules/strapi-database/lib/database-manager.js:43:5)
strapi     |     at async Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:354:5)
strapi     |     at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:9)
strapi exited with code 1
```

**Comment by cyp3rius** [comment]
Hello @apokalipscke,

What you're doing is correct. Plugin has been removed but I think you forgot to manually amend the changed in your collections you already done by adding attribute relation to navigation item. Am I correct?

**Comment by apokalipscke** [comment]
I tried it the same minute you wrote this 😂 .

It worked, I just forgot to remove this
```json
"navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
}
```
from my model settings.

Thanks!

**Comment by apokalipscke** [comment]
@cyp3rius 

But the tables still exist in database. Don't know if this is an issue ...

**Comment by cyp3rius** [comment]
That's the strapi stuff :) I'm not expecting the tables are going to be removed automatically, also when you're changing the other models. 

We didn't "automate" by our own it to avoid problems with if someone made an extensions to the plugin.
